- README.md
- setup.py
> Add python_requires to setup.py

- .coveragerc
- .travis.yml
- RELEASING.md
- setup.cfg
- setup.py
- src/tinytext/__init__.py
- src/tinytext/cli.py
Using PyPI's API token beta:
* https://pypi.org/help/#apitoken
>  Use setuptools_scm to simplify versioning and auto-deploy to PyPI

- .coveragerc
- .pre-commit-config.yaml
- codecov.yml
- tox.ini
https://nedbatchelder.com/blog/201908/dont_omit_tests_from_coverage.html
> Cover tests

- .github/workflows/test.yml
- .gitignore
- .pre-commit-config.yaml
- setup.py
- src/tinytext/__init__.py
- tests/test_tinytext.py
- tox.ini
Plus add flake8-2020 to pre-commit and do some misc tidy-ups.
> Add mypy type checking and more tests with hypothesis-auto

- .github/workflows/release.yml
- .pre-commit-config.yaml
- .travis.yml
- tox.ini
Uses https://github.com/actions/create-release.
Also test on Python 3.9-dev to avoid surprises
> Add GitHub Action to create a release from a tag

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
Use release drafter to draft releases using Keep a Changelog headings.
* https://github.com/release-drafter/release-drafter
* https://keepachangelog.com/en/1.0.0/
> Use release drafter to draft releases

- .github/labels.yml
- .github/workflows/labels.yml
* `.github/labels.yml` defines the labels
* `.github/workflows/labels.yml` runs the action to sync the labels
Uses the https://github.com/micnncim/action-label-syncer GHA
> Sync issue labels using GitHub Actions

- .github/labels.yml
- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
Put "changelog: " in front for clarity.
> Prefix changelog labels

- .github/workflows/deploy.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- .travis.yml
- tox.ini
Token no longer needed:
* https://community.codecov.io/t/whitelist-github-action-servers-to-upload-without-a-token/491/17?u=hugovk
> No need for token to upload to Codecov

- .github/workflows/test.yml
- .pre-commit-config.yaml
Using deadsnakes: https://github.com/actions/setup-python/issues/20#issuecomment-596221879
> GHA: Test on Python 3.9-dev

- .github/workflows/deploy.yml
- .github/workflows/test.yml
- .pre-commit-config.yaml
- .travis.yml
- Gruntfile.js
- RELEASING.md
- pyproject.toml
- setup.py
Also move config to pyproject.toml, requires setuptools>=44
And some other minor things
> Use setuptools_scm>=3.5 to use no-local-version

- .github/workflows/automerge.yml
https://github.com/pascalgn/automerge-action
> Add GHA to automerge PRs

- .github/labels.yml
Follow up to https://github.com/hugovk/tinytext/pull/35.
> Add automerge label to label syncer

- .github/workflows/test.yml
Like https://github.com/hugovk/tinytext/pull/39 but for 3.10.
> Use deadsnakes/action for Python 3.10-dev

- .github/workflows/lint.yml
- .github/workflows/test.yml
- .pre-commit-config.yaml
- tests/test_tinytext.py
- tox.ini
Plus some other minor updates.
> Force colour output on GitHub Actions

- .github/workflows/test.yml
- setup.py
Benefit over deadsnakes: can test on all OS versions.
> Test Python 3.9-dev on GitHub Actions

- README.md
https://twitter.com/hugovk/status/1317130592652316672
> Migrate Travis CI to .com

- .travis.yml
> Add Python 3.9 final to Travis CI

- .github/workflows/deploy.yml
- .github/workflows/test.yml
Committed via https://github.com/asottile/all-repos
> Upgrade to actions/setup-python@v3

- .github/workflows/test.yml
- .pre-commit-config.yaml
- setup.cfg
- tox.ini
* Add changelog to project URLs
* Add pyproject-fmt and tox-ini-fmt to pre-commit
> Add support for Python 3.11

- .github/renovate.json
https://docs.renovatebot.com/configuration-options/#schedule
https://docs.renovatebot.com/presets-schedule/#schedulemonthly
> Run Renovate on the first of the month

- .github/workflows/deploy.yml
- pyproject.toml
- requirements.txt
- tests/test_tinytext.py
Committed via https://github.com/asottile/all-repos
> Replace deprecated repository_url with repository-url

- pyproject.toml
* Already tested against `3.12-dev`
* Add the Trove classifier
> Add support for Python 3.12

- .pre-commit-config.yaml
Check for files with names that would conflict on a case-insensitive filesystem like macOS HFS+ or Windows FAT.
> Add check-case-conflict

- .github/workflows/deploy.yml
* Always build and inspect.
* Upload to Test PyPI on every commit on main.
* Upload to real PyPI on GitHub Releases.
> Use hynek/build-and-inspect-python-package

- .github/workflows/test.yml
- .pre-commit-config.yaml
- pyproject.toml
- tox.ini
The first alpha was released last week:
https://discuss.python.org/t/python-3-13-0-alpha-1/36109?u=hugovk
> Add support for Python 3.13
