- .pre-commit-config.yaml
Mainly to test the latest changes to PyPI's token upload beta, by deploying to Test PyPI on a master merge.
* https://pythoninsider.blogspot.com/2019/07/pypi-now-supports-uploading-via-api.html
* https://discuss.python.org/t/pypi-security-work-multifactor-auth-progress-help-needed/1042/43
The old stuff changed in https://github.com/hugovk/tinytext/commit/5dd6f4f37f34e355fdac2be6f6be8f7f25b3fbd1 has been removed from PyPI (Warehouse).
> Add pyupgrade to pre-commit

- .coveragerc
- .github/workflows/lint.yml
- .github/workflows/test.yml
- .pre-commit-config.yaml
- LICENSE.txt
- README.md
- pyproject.toml
- setup.cfg
- setup.py
- src/tinytext/__init__.py
- src/tinytext/cli.py
- tests/__init__.py
- tests/test_tinytext.py
- tox.ini
For coverage:
1. Get a Codecov upload token:
* https://docs.codecov.io/docs/frequently-asked-questions#section-where-is-the-repository-upload-token-found- 
* https://codecov.io/gh/hugovk/tinytext/settings
2. Save it as `CODECOV_TOKEN` at https://github.com/hugovk/tinytext/settings/secrets
This probably won't work for forks. Azure Pipelines has a workaround to "Make secrets available to builds of forks":
* https://hynek.me/articles/simple-python-azure-pipelines/#coverage
And with this AP workaround:
> Please note that this token can leak despite being a “secret” variable. A malicious user can open a PR and send it anywhere they want. However, the token is worthless for anything except uploading coverage and it’s easy to see when someone does it.
So a GHA workaround would be to put the …
> Test with GitHub Actions

- .github/workflows/lint.yml
- .github/workflows/test.yml
- .gitignore
- .pre-commit-config.yaml
- .travis.yml
- Gruntfile.js
- MANIFEST.in
- README.md
- RELEASING.md
- setup.cfg
When using setuptools_scm, MANIFEST.in is needed when we want to exclude tracked files, or include untracked files.
* https://github.com/pypa/setuptools_scm/blob/master/README.rst#file-finders-hook-makes-most-of-manifestin-unnecessary
---
Also adjustments to testing and formatting, see commit messages for details.
> Remove MANIFEST.in + testing updates

- .pre-commit-config.yaml
- README.md
- setup.cfg
The wheel filename contained `py2.py3`, indicating Python 2 support.
> _Universal Wheels_ are wheels that are pure Python (i.e. contain no compiled extensions) and support Python 2 and 3. This is a wheel that can be installed anywhere by pip.
...
> Only use the `--universal` setting, if:
> * Your project runs on Python 2 and 3 with no changes (i.e. it does not require 2to3).
> * Your project does not have any C extensions.
>
> Beware that `bdist_wheel` does not currently have any checks to warn if you use the setting inappropriately.
https://packaging.python.org/guides/distributing-packages-using-setuptools/#universal-wheels
> _Pure Python Wheels_ that are not “universal” are wheels that are pure Python (i.e. contain no compiled extensions), but don’t natively support both Python 2 and 3. …
> Only Python 3 is supported: don't create universal wheel

- .travis.yml
Follow on from #23.
This reverts commit e0ee70403d844064e7726e8fe6f835d638388620, which didn't do what it said...
So only deploy from GHA, not from Travis CI.
> Fix "Don't deploy from Travis CI"

- .github/workflows/deploy.yml
2.3.5 wasn't deployed to PyPI, because the Action didn't trigger.
I think this is because I didn't push a tag, like when manually deploying, but it was created when the draft release was published.
Let's try this. It's possible `if: startsWith(github.event.ref, 'refs/tags')` won't match, but we'll see.
> Trigger on published release

- .github/workflows/deploy.yml
Continuation of https://github.com/hugovk/tinytext/pull/23 and https://github.com/hugovk/tinytext/pull/27.
2.3.6 wasn't deployed to PyPI, the Action triggered but as expected, the step was skipped because `if: startsWith(github.event.ref, 'refs/tags')` didn't match.
(Could also check `github.event_name == 'release' &&`, but this should be enough.)
> Deploy to PyPI when event = published

- .github/workflows/test.yml
- RELEASING.md
Now it's possible to find the cache directory with `pip cache dir` using pip 20.1, which means a lot of cache config can be removed.
This needs pip 20.1+ to be installed first, and so needs Python to be set up first, to make sure it's using the correct Python 3 and not some Python 2 from the default image.
Also install wheel, so pip can create wheels, which should speed up subsequent builds from cache.
> Simplify cache config with 'pip cache dir'

- .github/workflows/deploy.yml
- .github/workflows/lint.yml
- .pre-commit-config.yaml
- setup.py
https://github.com/hugovk/tinytext/pull/31 resulted in https://test.pypi.org/project/tinytext/0.0.0/
> to use `setup.py` as you write, you either need the latest `setuptools` and the latest `setuptools_scm` pre-installed or as `setup_requires` in `setup.py/cfg`,
> 
> `setup.py` invocations will **NOT** install build requirements from `pyproject.toml`
> 
> if you have a modern pip installed, i believe a `pip wheel .` should produce the desired results
https://github.com/pypa/setuptools_scm/issues/386#issuecomment-585075432
> Fix setuptools_scm generating version 0.0.0

- .github/workflows/deploy.yml
- .github/workflows/lint.yml
- pyproject.toml
- setup.py
Revert changes from https://github.com/hugovk/tinytext/pull/31 and https://github.com/hugovk/tinytext/pull/33 for now, the last test deploy was also version 0.0.0.
```
Uploading distributions to https://test.pypi.org/legacy/
Uploading tinytext-0.0.0-py3-none-any.whl
0%|          | 0.00/10.5k [00:00<?, ?B/s]
100%|██████████| 10.5k/10.5k [00:00<00:00, 18.6kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 400 Client Error: File already exists. See https://test.pypi.org/help/#file-name-reuse for url: https://test.pypi.org/legacy/
```
https://github.com/hugovk/tinytext/actions/runs/90871992
Keep some of the unrelated changes.
> Revert the no-local-version changes, keep local_scheme

- .github/workflows/automerge.yml
It seems to actually delete the label from the repo as well, and the label needs to be created again next time.
Hopefully this won't happen now.
> Don't remove automerge label

- .github/workflows/deploy.yml
- .pre-commit-config.yaml
- .travis.yml
* https://github.com/actions/checkout/releases/tag/v2.2.0
* https://github.com/actions/checkout/pull/258
We can remove some config.
Also test on Python 3.10-dev on Travis CI and update pre-commit.
> GHA: actions/checkout v2.2 can fetch all tags

- .github/workflows/test.yml
Now available in preview.
> The list of the tools that are not available on Ubuntu 20.04 yet (It should be available in a few weeks):
> 1. Docker
> 2. Pre-cached versions of **Python**, PyPy, Ruby, Node (**setup-python** / UsePython, setup-ruby / UseRuby tasks may not work properly due to that).
https://github.com/actions/virtual-environments/issues/228#issuecomment-637362224
---
However the deadsnakes versions pass ✅
* https://github.com/hugovk/tinytext/blob/e98981b0c126737a766046a4b8a6b4385b02f567/.github/workflows/test.yml#L18-L29
> GHA: Test on Ubuntu 20.04 LTS (Focal Fossa)

- setup.py
I added the Trove supporting statement for Python 3.9 as per #54 , but unfortunately when I attempted to enable "python-3.9" in Travis, it's not available yet, only python-3.9-dev which you're already running against.
Maybe I was too quick, and Travis CI will enable it in the next week or so?
> Add supporting statement for Python 3.9

- .github/workflows/test.yml
- .travis.yml
- setup.py
- tox.ini
Also test macOS 11.
macOS 11.0 is in preview, and PyPy3 not yet available, so skip that for now: https://github.com/actions/setup-python/issues/158
> Support PyPy3

- .github/release-drafter.yml
- .pre-commit-config.yaml
- .zenodo.json
- README.md
Let's see if this will link names with their Orcid:
https://zenodo.org/record/4071429#.X8DZqar7TUJ
> Add Zenodo record metadata

- .github/workflows/require-pr-label.yml
Require one of the "changelog: X" labels on PRs.
https://github.com/mheap/github-action-required-labels
> GHA: Require changelog label on PRs

- .github/workflows/deploy.yml
- .github/workflows/test.yml
- .pre-commit-config.yaml
- pyproject.toml
- setup.cfg
- tox.ini
| cycle | latest |  release   |    eol     |
|:------|:-------|:----------:|:----------:|
| 3.10  | 3.10.0 | 2021-10-04 | 2026-10-04 |
| 3.9   | 3.9.9  | 2020-10-05 | 2025-10-05 |
| 3.8   | 3.8.12 | 2019-10-14 | 2024-10-14 |
| 3.7   | 3.7.12 | 2018-06-27 | 2023-06-27 |
| 3.6   | 3.6.15 | 2016-12-23 | 2021-12-23 |
> Drop support for soon-EOL Python 3.6

- .github/dependabot.yml
Docs:
* https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#specifying-dependencies-and-versions-to-ignore
> Dependabot: Only major update for GitHub Actions

- .github/workflows/test.yml
To simplify required checks in branch protection rules.
> CI: Add final noop job to mark as required

- .github/workflows/deploy.yml
These are now removed from the docs at https://github.com/pypa/gh-action-pypi-publish because it's the default.
> Remove default "user: __token__"

- .pre-commit-config.yaml
- pyproject.toml
We can use Black's new `target-version` inference to remove some config:
https://ichard26.github.io/blog/2023/01/black-23.1.0/#better-default-for---target-version-if-pep-621-python-requires-is-available
> Update pyproject-fmt and Black

- .github/workflows/test.yml
Re: https://github.com/actions/setup-python/releases/tag/v4.6.0
> Allow pre-releases to remove '-dev' suffix

- .flake8
- .github/workflows/lint.yml
- .github/workflows/test.yml
- .pre-commit-config.yaml
- pyproject.toml
- src/tinytext/__init__.py
- tox.ini
Changes proposed in this pull request:
* Drop support for Python 3.7, EOL this month
* https://devguide.python.org/versions/
* https://peps.python.org/pep-0537/
* Not planning a major bump, `requires-python = ">=3.8"` makes sure people get the right version
> Drop support for EOL Python 3.7

- .gitignore
- pyproject.toml
- src/tinytext/__init__.py
With Python 3.12.4:
```sh
python -X importtime -c "import tinytext" 2> import.log && tuna import.log
```
Cuts out the 22ms `importlib.metadata` import.
```console
❯ hyperfine -w 8 "tinytext --version"
Benchmark 1: tinytext --version
Time (mean ± σ):      49.2 ms ±   3.7 ms    [User: 38.2 ms, System: 9.5 ms]
Range (min … max):    45.1 ms …  66.4 ms    62 runs
```
```console
❯ hyperfine -w 8 "tinytext --version"
Benchmark 1: tinytext --version
Time (mean ± σ):      26.4 ms ±   1.0 ms    [User: 19.8 ms, System: 5.5 ms]
Range (min … max):    24.6 ms …  29.1 ms    105 runs
```
> Generate `__version__` at build to avoid slow `importlib.metadata` import

- .github/workflows/test.yml
- pyproject.toml
- tox.ini
Python 3.8 is end-of-life next month:
* https://devguide.python.org/versions/
* https://peps.python.org/pep-0569/#lifespan
> Drop support for Python 3.8

- .github/workflows/lint.yml
No Actions cache: 1m 6s
https://github.com/hugovk/tinytext/actions/runs/11307458441/job/31449206647
With Actions cache: 13s
https://github.com/hugovk/tinytext/actions/runs/11307515313/job/31449323869
No Actions cache: 50s
https://github.com/hugovk/tinytext/actions/runs/11307553771/job/31449400169
With Actions cache: 13s
https://github.com/hugovk/tinytext/actions/runs/11307560729/job/31449415202
> Use pre-commit-uv for lint

- src/tinytext/__init__.py
- tests/test_tinytext.py
This Pull Request adds an superscript equivalent support to the digits 0-9 from the English Keyboard with their equivalent tiny unicode superscripts added in the newly renamed tiny_characters (from tiny_letters) dictionary collection, and includes a testcase for testing these digits coversion as well.
I have directly raised it as a pull request for the feature addition, since there was no CONTRIBUTING.md asking for an issue first, but a reviewer can indicate if those entries are also needed for it and I can help with it. Please have a review and let me know of your comments, if any.
> Add numerical digits superscript conversion

- .github/workflows/deploy.yml
- .github/workflows/lint.yml
- .github/workflows/require-pr-label.yml
Generating PyPI's digital attestations should be enough (https://docs.pypi.org/attestations/), we don't _also_ need to use https://github.com/actions/attest-build-provenance.
> Only create PyPI digital attestations (PEP 740)

- src/tinytext/cli.py
Will be available for 3.14 beta:
https://docs.python.org/3.14/library/argparse.html#color
> Enable colour help for Python 3.14
